version: "3.9"

services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./config/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - term-paper

volumes:
  mongodb-data:

networks:
  term-paper:
